server:
  error:
    include-stacktrace: on_param

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://35.193.137.179:3306/meusgastos?useSSL=false
    username: root
    password: Q6a/%|T%y:-YauVB
    driver-class-name: com.mysql.jdbc.Driver